services:  
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/etc/data
    
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  
volumes:
  postgres-data:
    driver: local